### ISSUE TITLE
addEvent 支持 passive event

### ISSUE THREAD

**Issue by toxic-johann** [Chimeejs/chimee-helper-dom#1]
现阶段 addEvent 尚未支持 passive 选项。

根据 [chimee #38](https://github.com/Chimeejs/chimee/issues/38) 反映，希望将部分事件支持 passive 监听。

具体做法如此[文章](https://segmentfault.com/a/1190000007913386)

关键性代码如下：

```javascript
// Test via a getter in the options object to see 
// if the passive property is accessed
var supportsPassive = false;
try {
  var opts = Object.defineProperty({}, 'passive', {
    get: function() {
      supportsPassive = true;
    }
  });
  window.addEventListener("test", null, opts);
} catch (e) {}

// Use our detect's results. 
// passive applied if supported, capture will be false either way.
elem.addEventListener(
  'touchstart',
  fn,
  supportsPassive ? { passive: true } : false
); 
```

建议解决方案，在 chimee-helper-dom 中作出 浏览器是否对 passive 支持的判断，对外暴露 passive 选项。

**Comment by huzunjie** [comment]
已修改并export supportsPassive 。

addEvent (el, type, handler, once,  { passive: true } ) 即可在支持 passive 的环境启用相应配置。
